# Generated by Django 4.1.7 on 2023-03-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('proof', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rickhouseapi.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rickhouseapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='WhiskeyDistillery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rickhouseapi.distillery')),
                ('whiskey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_whiskey', to='rickhouseapi.whiskey')),
            ],
            options={
                'unique_together': {('whiskey', 'distillery')},
            },
        ),
        migrations.AddField(
            model_name='distillery',
            name='whiskey',
            field=models.ManyToManyField(through='rickhouseapi.WhiskeyDistillery', to='rickhouseapi.whiskey'),
        ),
    ]
